### ISSUE TITLE
大佬能支持AppCompatActivity吗

### ISSUE THREAD

**Issue by geeklx** [han1202012/Plugin_Hook#1]
大佬能支持AppCompatActivity吗 谢谢回复

**Comment by geeklx** [comment]
支持后加上这句不报错
    //
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

**Comment by han1202012** [comment]
开发的时候 需要 自定义 Hook 插件框架 吗 , 如果是 AppCompatActivity 需要 设置的 HOOK 点不一样 , Activity 与 AppCompatActivity 的 HOOK 点不同 , Activity 的 mResources 在 ContextThemeWrapper 类里面 , AppCompatActivity  的 mResources  就在 AppCompatActivity  中定义

**Comment by geeklx** [comment]
开发的级联的库都是放在plugin库中报错，提示就是AppCompatActivity的问题，怎么解决，如何适配AppCompatActivity

**Comment by geeklx** [comment]
我的QQ：729490254 请大佬指点

**Comment by han1202012** [comment]
Activity 与 AppCompatActivity 就一个点不同 , 就是资源所在的类 ; 
在 InstrumentationProxy 中的 exchangeResourcesOfActivity 方法中 , 通过反射获取 ContextThemeWrapper 中的 mResources 字段 , 然后替换成插件包加载的 资源 ; 

        // 反射 ContextThemeWrapper 类 , Activity 是 ContextThemeWrapper 的子类
        // Resources mResources 成员定义在 ContextThemeWrapper 中
        Class<?> contextThemeWrapperClass = null;
        try {
            contextThemeWrapperClass = Class.forName("android.view.ContextThemeWrapper");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

        // 反射获取 ContextThemeWrapper 类的 mResources 字段
        Field mResourcesField = null;
        try {
            mResourcesField = contextThemeWrapperClass.getDeclaredField("mResources");
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }

将上面的 "android.view.ContextThemeWrapper" 替换成 "androidx.appcompat.app.AppCompatActivity" 应该就可以了 , 其它的地方都是一样的 ;

**Comment by geeklx** [comment]
按照大佬说的改过了，还是报错：
Process: com.example.pluginstandard_that, PID: 23251
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java:530)
        at androidx.appcompat.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:151)
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1383)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3545)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2099)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7892)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by geeklx** [comment]
写法：
 public void setRes() {
        // 反射 ContextThemeWrapper 类 , Activity 是 ContextThemeWrapper 的子类
        // Resources mResources 成员定义在 ContextThemeWrapper 中
        Class<?> contextThemeWrapperClass = null;
        try {
            contextThemeWrapperClass = Class.forName("androidx.appcompat.app.AppCompatActivity");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

        // 反射获取 ContextThemeWrapper 类的 mResources 字段
        // 反射获取 AppCompatActivity 类的 mResources 字段
        try {
            Field mResourcesField = contextThemeWrapperClass.getDeclaredField("mResources");
            // 设置字段可见性
            mResourcesField.setAccessible(true);
            // 将插件资源设置为
            mResourcesField.set(context, getResources());
        } catch (IllegalAccessException | NoSuchFieldException e) {
            e.printStackTrace();
        }
    }

**Comment by geeklx** [comment]
单纯的使用代码是没问题的，但是引入不同的第三方库，就会报错，上面的错误，plugin的app不可能不用第三方库，所以请大佬指点一下怎么解决上面的问题

**Comment by curry-wei** [comment]
运行host 跳转插件报错 请问什么原因？
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.plugin/com.example.plugin.MainActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by curry-wei** [comment]
@han1202012 运行host 跳转插件报错 请问什么原因？
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.plugin/com.example.plugin.MainActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by lantianwhq** [comment]
2022-11-26 17:19:54.116 8380-8396/com.example.plugin_hook D/AppScoutStateMachine: 8380-ScoutStateMachinecreated
2022-11-26 17:19:56.961 8380-8380/com.example.plugin_hook W/ple.plugin_hoo: Accessing hidden method Landroid/app/Instrumentation;->execStartActivity(Landroid/content/Context;Landroid/os/IBinder;Landroid/os/IBinder;Landroid/app/Activity;Landroid/content/Intent;ILandroid/os/Bundle;)Landroid/app/Instrumentation$ActivityResult; (unsupported, reflection, allowed)
2022-11-26 17:19:56.965 8380-8380/com.example.plugin_hook W/System.err: java.lang.reflect.InvocationTargetException
2022-11-26 17:19:56.967 8380-8380/com.example.plugin_hook W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-11-26 17:19:56.967 8380-8380/com.example.plugin_hook W/System.err:     at kim.hsl.plugin.Reflector.call(Reflector.java:232)
2022-11-26 17:19:56.967 8380-8380/com.example.plugin_hook W/System.err:     at kim.hsl.plugin.InstrumentationProxy.execStartActivity(InstrumentationProxy.java:49)
2022-11-26 17:19:56.968 8380-8380/com.example.plugin_hook W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:5532)
2022-11-26 17:19:56.968 8380-8380/com.example.plugin_hook W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:5485)
2022-11-26 17:19:56.968 8380-8380/com.example.plugin_hook W/System.err:     at android.app.Activity.startActivity(Activity.java:5891)
2022-11-26 17:19:56.968 8380-8380/com.example.plugin_hook W/System.err:     at android.app.Activity.startActivity(Activity.java:5844)
2022-11-26 17:19:56.968 8380-8380/com.example.plugin_hook W/System.err:     at com.example.plugin_hook.MainActivity2$1.onClick(MainActivity2.java:64)
2022-11-26 17:19:56.968 8380-8380/com.example.plugin_hook W/System.err:     at android.view.View.performClick(View.java:7753)
2022-11-26 17:19:56.968 8380-8380/com.example.plugin_hook W/System.err:     at android.view.View.performClickInternal(View.java:7730)
2022-11-26 17:19:56.969 8380-8380/com.example.plugin_hook W/System.err:     at android.view.View.access$3700(View.java:861)
2022-11-26 17:19:56.969 8380-8380/com.example.plugin_hook W/System.err:     at android.view.View$PerformClick.run(View.java:29136)
2022-11-26 17:19:56.969 8380-8380/com.example.plugin_hook W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2022-11-26 17:19:56.969 8380-8380/com.example.plugin_hook W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-11-26 17:19:56.969 8380-8380/com.example.plugin_hook W/System.err:     at android.os.Looper.loopOnce(Looper.java:210)
2022-11-26 17:19:56.969 8380-8380/com.example.plugin_hook W/System.err:     at android.os.Looper.loop(Looper.java:299)
2022-11-26 17:19:56.969 8380-8380/com.example.plugin_hook W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8118)
2022-11-26 17:19:56.970 8380-8380/com.example.plugin_hook W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-11-26 17:19:56.970 8380-8380/com.example.plugin_hook W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
2022-11-26 17:19:56.970 8380-8380/com.example.plugin_hook W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2022-11-26 17:19:56.971 8380-8380/com.example.plugin_hook W/System.err: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.plugin/com.example.plugin.MainActivity}; have you declared this activity in your AndroidManifest.xml?
2022-11-26 17:19:56.971 8380-8380/com.example.plugin_hook W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2085)
2022-11-26 17:19:56.971 8380-8380/com.example.plugin_hook W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)

**Comment by lantianwhq** [comment]
同样的问题

**Comment by tomyZhou** [comment]
Accessing hidden method Landroid/app/Instrumentation;->execStartActivity

**Comment by tomyZhou** [comment]
为什么我点击打开插件Activity的时候，AmsInvocationHandler里invoke没有调用startActivity方法
